COYI/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#landing'
  devise_for :users, controllers: {registrations: 'users/registrations'}


  get 'askanexpert', to: 'ask_advocates#index', as: 'ask_expert'
  get 'profile/projects/new', to: 'projects#new', as: 'new_project'
  get 'profile/projects/:id', to: 'projects#show_user_project', as: 'show_user_project'


  get 'profile/my_resources/new', to: 'my_resources#new', as: 'new_my_resource'
  get 'profile/my_resources/:id', to: 'my_resources#show', as: 'show_user_my_resource'

  get 'circle/global',    to: 'circle#global',      as: 'global'
  get 'circle/advocate',  to: 'circle#advocate',    as: 'advocate'
  get 'circle/rules',     to: 'circle#rules',       as: 'rules'



  get 'home',             to: 'home#home',          as: 'home'

  get 'about',            to: 'about#about',        as: 'about'
  get 'contact',          to: 'about#contact',      as: 'contact'
  get 'faq',              to: 'about#faq',          as: 'faq'

  get 'resources',        to: 'my_resources#index', as: 'resources'

  get 'success',          to: 'success#success',    as: 'stories'

  get 'users',            to: 'profile#profile'

  resources :challenges
  resources :resources
  resources :my_resources
  resources :news
  resources :projects
  resources :chapters
  resources :ask_advocates


  get 'profile/projects', to: 'projects#user_projects', as: 'user_projects'
  get 'profile/my_resources', to: 'my_resources#user_my_resource', as: 'user_my_resources'
  get 'profile/me',         to: 'profile#profile',    as: 'user_profile'
  get 'users/me/edit',    to: 'devise/registrations#update'
  get 'users/:id',        to: 'profile#show'
  get 'chapter/news', to: 'news#chapter_news', as: 'chapter_news'


  resources :my_resources, only: [:create, :new]

  post 'contact', to: 'about#create'

end

COYI/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

COYI/app/models/ask_advocate.rb
class AskAdvocate < ApplicationRecord
  has_many :users
end

COYI/app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user

  validates_format_of :emailaddress,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates_format_of :firstname, :with => /\A[a-zA-Z]+\z/
  validates_format_of :lastname, :with => /\A[a-zA-Z]+\z/
  validates :location, :organisation, presence: true
end

COYI/app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :users
  has_many :projects, through: :user
end

COYI/app/models/my_resource.rb
class MyResource < ApplicationRecord
  enum status: [:"Awaiting Approval", :Approved, :Rework, :Rejected]
  belongs_to :user
  has_one :chapter, through: :user
  validates :title, :description, presence: true
  has_one_attached :uploaded_file
end

COYI/app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
end

COYI/app/models/project.rb
class Project < ApplicationRecord
  enum status: [:"Awaiting Approval", :Approved, :Rework, :Rejected]
  belongs_to :user
  has_one :chapter, through: :user
  validates :title, :description, presence: true
  has_many_attached :uploaded_files
  validates :title, length: { minimum: 8, too_short: "Title too short. Try and enter a descriptive title" }
  validates :title, length: { maximum: 30, too_long: "Title too long. %{count} characters is the maximum allowed"  }
end

COYI/app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_save :default_access_level
  def default_access_level
     self.access_level ||= 1
  end
  belongs_to :chapter
  has_many :projects
  has_many :challenges
  has_many :email_to, :class_name => 'AskAdvocate', :foreign_key => 'email_to_id'
  has_many :news

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, authentication_keys: [:login]

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  elsif conditions.has_key?(:username) || conditions.has_key?(:email)
    where(conditions.to_h).first
    end
  end

  validates :email, presence: :true, uniqueness: { case_sensitive: false }
  # validate :validate_username
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :first_name, :second_name, :email, :location, :country, presence: true
  validates :first_name, :second_name, :country, :location, format: { with: /\A[a-z A-Z]+\z/, message: "No special characters or numbers, only letters" }

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  validate :password_complexity

  def password_complexity
   if password.present?
      if !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\p{Punct})/)
        errors.add :password, "must include at least one lowercase letter, one uppercase letter, one number, and a special character"
      end
   end
  end

end

COYI/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def landing
  end
end

COYI/app/controllers/my_resources_controller.rb
class MyResourcesController < ApplicationController
  before_action :set_my_resource, only: [:show, :edit, :update, :destroy]
  # Only allows logged in users to access those methods
  before_action :authenticate_user!, only: [:user_my_resources, :new, :edit, :create, :destroy]

  def level
    authorize :resource, :level?
  end

  # GET /my_resources
  # GET /my_resources.json
  def index
    @my_resources = MyResource.where(status: 0)

  end

  # GET /my_resources/1
  # GET /my_resources/1.json
  def show
  end

  # GET /my_resources/new
  def new
    @my_resource = MyResource.new
  end

  # GET /my_resources/1/edit
  def edit
  end

  def user_my_resource
    @my_resources = MyResource.where(user_id: current_user.id)
    @ask_advocates = AskAdvocate.where(user_id: current_user.id)

  end

  # POST /my_resources
  # POST /my_resources.json
  def create
    @my_resource = MyResource.create!(my_resource_params)
    @my_resource.status = 0
    respond_to do |format|
      if @my_resource.save
        format.html { redirect_to @my_resource, notice: 'My resource was successfully created.' }
        format.json { render :show, status: :created, location: @my_resource }
      else
        format.html { render :new }
        format.json { render json: @my_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_resources/1
  # PATCH/PUT /my_resources/1.json
  def update
    respond_to do |format|
      if @my_resource.update(my_resource_params)
        format.html { redirect_to @my_resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_resource }
      else
        format.html { render :edit }
        format.json { render json: @my_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_resources/1
  # DELETE /my_resources/1.json
  def destroy
    @my_resource.destroy
    respond_to do |format|
      format.html { redirect_to my_resources_url, notice: 'My resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_resource
      @my_resource = MyResource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_resource_params
      params.require(:my_resource).permit(:title, :description, :status, :uploaded_file).merge(user_id: current_user.id)
    end
end

COYI/app/helpers/about_helper.rb
module AboutHelper
end

COYI/app/helpers/application_helper.rb
module ApplicationHelper
end

COYI/app/helpers/challenges_helper.rb
module ChallengesHelper
end

COYI/app/helpers/chapters_helper.rb
module ChaptersHelper
end

COYI/app/helpers/circle_helper.rb
module CircleHelper
end

COYI/app/helpers/home_helper.rb
module HomeHelper
end

COYI/app/helpers/my_resources_helper.rb
module MyResourcesHelper
end

COYI/app/helpers/news_helper.rb
module NewsHelper
end

COYI/app/helpers/profile_helper.rb
module ProfileHelper
end

COYI/app/helpers/projects_helper.rb
module ProjectsHelper
end

COYI/app/helpers/resources_helper.rb
module ResourcesHelper
end

COYI/app/helpers/success_helper.rb
module SuccessHelper
end

COYI/app/helpers/user_helper.rb
module UserHelper
end

COYI/app/views/my_resources/_form.html.erb
<%= form_with(model: my_resource, local: true) do |form| %>
  <% if my_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_resource.errors.count, "error") %> prohibited this my_resource from being saved:</h2>

      <ul>
      <% my_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="white-text text-on-bk-red pad">

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.file_field :uploaded_file%>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

COYI/app/views/my_resources/edit.html.erb
<h1>Editing My Resource</h1>

<%= render 'form', my_resource: @my_resource %>

<%= link_to 'Show', @my_resource %> |
<%= link_to 'My Resources', user_my_resources_path %>

COYI/app/views/my_resources/index.html.erb
<h1>Resources</h1>

<div class="container white-text">
  <div class="row">
    <div class="col-md-12">
      <div id="carouselExampleIndicators" class="carousel slide" class="caro" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="8"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="9"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="10"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="11"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="12"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="13"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="14"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="15"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="16"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <img class="d-block img-fluid" src="/slides/slide1.png" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide2.png" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide3.png" alt="Third slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide4.png" alt="Fourth slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide5.png" alt="Fifth slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide6.png" alt="Sixth slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide7.png" alt="Seventh slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide8.png" alt="Eigth slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide9.png" alt="Ninth slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide10.png" alt="Ten slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide11.png" alt="Eleven slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide12.png" alt="Twelve slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide13.png" alt="Thirteen slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide14.png" alt="Fourteen slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide15.png" alt="Fifteen slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="/slides/slide16.png" alt="Sixteen slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="sr-only">Previous</span></a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span><span class="sr-only">Next</span></a>
      </div>
    </div>
  </div>
  <div class="top-of-page"></div>
  <div class="row">
    <!-- We need a line or some small indication of which resources come from which level for higher levels -->
    <!-- Level 1 indication -->
    <% if policy(:resource).user_present? ||policy(:resource).level_1? || policy(:resource).level_2? || policy(:resource).level_5? %>
      <div class="col-md-4 first-column page-band-red pad">
        <ul class="docs">
          <%= render "resources/resourceslevel1" %>
        </ul>
      </div>
    <%end%>
      <!-- Level 2 indication -->
    <%if policy(:resource).level_2? || policy(:resource).level_5?%>
      <!-- level 3 and up -->
      <div class="col-md-4 second-column page-band-red pad">
        <ul class="docs">
          <%= render "resources/resourceslevel2-4"%>
        </ul>
      </div>
    <%end%>

      <!-- Level 5 indication -->
    <% if policy(:resource).level_5? %>
        <div class="col-md-4 third-column page-band-red pad">
          <ul class="docs">
            <%= render "resources/resourceslevel5" %>
          </ul>
        </div>
    <%end%>
  </div>

</div>

COYI/app/views/my_resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', my_resource: @my_resource %>

<%= link_to 'Back', user_my_resources_path %>

COYI/app/views/my_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @my_resource.title %></h1>
</p>

<p>
  <strong>Current Status:</strong>
  <%= @my_resource.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @my_resource.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @my_resource.user.email %>
</p>

<p>
  <a href="<%= rails_blob_path(@my_resource.uploaded_file, disposition: "attachment", only_path: true)%>"  download>Download Resource</a>
</p>


<%- if user_signed_in? %>
  <%= link_to 'Edit', edit_my_resource_path(@my_resource) %> |
  <%= link_to 'My Resources', user_my_resources_path %> |
<% else %>
<% end %>

<%= link_to 'Resources', resources_path %>

COYI/app/views/my_resources/user_my_resource.html.erb
<h1> <%= current_user.first_name%>'s Resources</h1>

<%= link_to 'New Resource', new_my_resource_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_resources.each do |my_resource| %>
      <tr>
        <td><%= link_to my_resource.title, my_resource %></td>
        <td><%= link_to my_resource.description, my_resource %></td>
        <td><%= my_resource.status %></td>
        <td><%= link_to 'Edit', edit_my_resource_path(my_resource) %></td>
        <td><%= link_to 'Destroy', my_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1> <%= current_user.first_name%>'s Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Question</th>
      <th>Email to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @ask_advocates.each do |ask_advocate| %>
  <tr>
    <td><%= ask_advocate.title %></td>
    <td><%= ask_advocate.body %></td>
    <td><%= ask_advocate.email_to %></td>
    <td><%= link_to 'Show', ask_advocate %></td>
    <td><%= link_to 'Destroy', ask_advocate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

COYI/app/views/my_resources/user_my_resources.html.erb
<h1> <%= current_user.first_name%>'s Resources</h1>

<%= link_to 'New Resource', new_my_resource_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_resources.each do |my_resource| %>
      <tr>
        <td><%= link_to my_resource.title, my_resource %></td>
        <td><%= link_to my_resource.description, my_resource %></td>
        <td><%= my_resource.status %></td>
        <td><%= link_to 'Edit', edit_my_resource_path(my_resource) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>