COYI/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#landing'
  devise_for :users, controllers: {registrations: 'users/registrations'}


  get 'askanexpert', to: 'ask_advocates#index', as: 'ask_expert'
  get 'profile/projects/new', to: 'projects#new', as: 'new_project'
  get 'profile/projects/:id', to: 'projects#show_user_project', as: 'show_user_project'


  get 'profile/my_resources/new', to: 'my_resources#new', as: 'new_my_resource'
  get 'profile/my_resources/:id', to: 'my_resources#show', as: 'show_user_my_resource'

  get 'circle/global',    to: 'circle#global',      as: 'global'
  get 'circle/advocate',  to: 'circle#advocate',    as: 'advocate'
  get 'circle/rules',     to: 'circle#rules',       as: 'rules'



  get 'home',             to: 'home#home',          as: 'home'

  get 'about',            to: 'about#about',        as: 'about'
  get 'contact',          to: 'about#contact',      as: 'contact'
  get 'faq',              to: 'about#faq',          as: 'faq'

  get 'resources',        to: 'my_resources#index', as: 'resources'

  get 'success',          to: 'success#success',    as: 'stories'

  get 'users',            to: 'profile#profile'

  resources :challenges
  resources :resources
  resources :my_resources
  resources :news
  resources :projects
  resources :chapters
  resources :ask_advocates


  get 'profile/projects', to: 'projects#user_projects', as: 'user_projects'
  get 'profile/my_resources', to: 'my_resources#user_my_resource', as: 'user_my_resources'
  get 'profile/me',         to: 'profile#profile',    as: 'user_profile'
  get 'users/me/edit',    to: 'devise/registrations#update'
  get 'users/:id',        to: 'profile#show'
  get 'chapter/news', to: 'news#chapter_news', as: 'chapter_news'


  resources :my_resources, only: [:create, :new]

  post 'contact', to: 'about#create'

end

COYI/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

COYI/app/models/ask_advocate.rb
class AskAdvocate < ApplicationRecord
  has_many :users
end

COYI/app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user

  validates_format_of :emailaddress,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates_format_of :firstname, :with => /\A[a-zA-Z]+\z/
  validates_format_of :lastname, :with => /\A[a-zA-Z]+\z/
  validates :location, :organisation, presence: true
end

COYI/app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :users
  has_many :projects, through: :user
end

COYI/app/models/my_resource.rb
class MyResource < ApplicationRecord
  enum status: [:"Awaiting Approval", :Approved, :Rework, :Rejected]
  belongs_to :user
  has_one :chapter, through: :user
  validates :title, :description, presence: true
  has_one_attached :uploaded_file
end

COYI/app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
end

COYI/app/models/project.rb
class Project < ApplicationRecord
  enum status: [:"Awaiting Approval", :Approved, :Rework, :Rejected]
  belongs_to :user
  has_one :chapter, through: :user
  validates :title, :description, presence: true
  has_many_attached :uploaded_files
  validates :title, length: { minimum: 8, too_short: "Title too short. Try and enter a descriptive title" }
  validates :title, length: { maximum: 30, too_long: "Title too long. %{count} characters is the maximum allowed"  }
end

COYI/app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_save :default_access_level
  def default_access_level
     self.access_level ||= 1
  end
  belongs_to :chapter
  has_many :projects
  has_many :challenges
  has_many :email_to, :class_name => 'AskAdvocate', :foreign_key => 'email_to_id'
  has_many :news

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, authentication_keys: [:login]

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  elsif conditions.has_key?(:username) || conditions.has_key?(:email)
    where(conditions.to_h).first
    end
  end

  validates :email, presence: :true, uniqueness: { case_sensitive: false }
  # validate :validate_username
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :first_name, :second_name, :email, :location, :country, presence: true
  validates :first_name, :second_name, :country, :location, format: { with: /\A[a-z A-Z]+\z/, message: "No special characters or numbers, only letters" }

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  validate :password_complexity

  def password_complexity
   if password.present?
      if !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\p{Punct})/)
        errors.add :password, "must include at least one lowercase letter, one uppercase letter, one number, and a special character"
      end
   end
  end

end

COYI/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def landing
  end
end

COYI/app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create,  :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  def chapter_news
    @news = News.where(chapter_id: current_user.chapter_id)
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :story, :chapter_id).merge(user_id: current_user.id)
    end
end

COYI/app/helpers/about_helper.rb
module AboutHelper
end

COYI/app/helpers/application_helper.rb
module ApplicationHelper
end

COYI/app/helpers/challenges_helper.rb
module ChallengesHelper
end

COYI/app/helpers/chapters_helper.rb
module ChaptersHelper
end

COYI/app/helpers/circle_helper.rb
module CircleHelper
end

COYI/app/helpers/home_helper.rb
module HomeHelper
end

COYI/app/helpers/my_resources_helper.rb
module MyResourcesHelper
end

COYI/app/helpers/news_helper.rb
module NewsHelper
end

COYI/app/helpers/profile_helper.rb
module ProfileHelper
end

COYI/app/helpers/projects_helper.rb
module ProjectsHelper
end

COYI/app/helpers/resources_helper.rb
module ResourcesHelper
end

COYI/app/helpers/success_helper.rb
module SuccessHelper
end

COYI/app/helpers/user_helper.rb
module UserHelper
end

COYI/app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="container">
        <div class="form-div row">
          <div class="col-md-12" id="smooth-edges">
            <div class="advocate-div row">
              <div class="col-md-10 offset-md-1">

                <form class="" action="advocate.html.erb" method="post">
                  <p class="center-text">Enter your news story below</p>

                  <div class="no-margin field row">
                    <div class="col-md-12 center-text">
                      <%= form.label :title %>
                    </div>
                    <div class="col-md-6 offset-md-3">
                      <%= form.text_field :title, style: 'width:100%'%>
                    </div>
                  </div>

                  <br>

                  <div class="no-margin field row">
                    <div class="col-md-12 center-text">
                    <%= form.label :story %>
                    </div>
                    <div class="col-md-10 offset-md-1">
                      <%= form.text_area :story, style: 'width:100%;' %>
                    </div>
                  </div>
                  <br>
                  <div class="no-margin field row">
                    <div class="col-md-12 center-text">
                      <%= form.label :chapter_id %>
                    </div>
                    <div class="col-md-6 offset-md-3">
                      <%= form.collection_select :chapter_id, Chapter.all, :id, :name, style: 'width:100%;' %>
                    </div>
                  </div>
                  <br>
                  <div class="actions row">
                    <div class="col-md-6 offset-md-3">
                      <%= form.submit style: 'width:100%;'%>
                    </div>
                  </div>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

COYI/app/views/news/_news_list.html.erb
<div class="news-all">
  <% @news.each do |news| %>
    <div class="news-band-white">
      <div class="no-margin row" style="margin: 0;">
        <div class="col-md-6 news-title"><%= news.title %></div>
        <div class="col-md-6 news-title"><%= news.created_at %></div>
      </div>
      <div class="no-margin row news-body">
        <div class="col-md-9 offset-md-1 news-story"><%= news.story %></div>
        <div class="col-md-2"><%= link_to 'Read More', news %></div>
      </div>
      <div>
        <ul class="admin-list">
          <li class="edit-li"><%= link_to 'Edit', edit_news_path(news) %></li>
          <li class="edit-li"><%= link_to 'Delete', news, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </div>
      <div class="no-margin row">
        <div class="col-md-4 offset-md-2 news-author">Published by: <%= news.user.first_name + " " + news.user.second_name %></div>
      </div>
    </div>
  <% end %>
</div>

COYI/app/views/news/_show_news.html.erb
<div class="news-all">
    <div class="news-band-white">
      <div class="no-margin row" style="margin: 0;">
        <div class="col-md-6 news-title"><%= @news.title %></div>
        <div class="col-md-6 news-title"><%= @news.created_at %></div>
      </div>
      <div class="no-margin row news-body">
        <div class="col-md-9 offset-md-1 news-story"><%= @news.story %></div>
      </div>
      <div>
        <ul class="admin-list">
        </ul>
      </div>
      <div class="no-margin row">
        <div class="col-md-4 offset-md-2 news-author">Published by: <%= @news.user.first_name + " " + @news.user.second_name %></div>
        <div class="col-md-4 news-author"><%= Chapter.find(@news.chapter_id).name %></div>
      </div>
    </div>
</div>

COYI/app/views/news/chapter_news.erb
<link rel="stylesheet" href="/Stylesheets/news.css">
<p id="notice"><%= notice %></p>
<h1>Chapter News</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Story</th>
      <th>Published</th>
      <th>User</th>
      <th>Chapter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.story %></td>
        <td><%= news.created_at %></td>
        <td><%= User.find(news.user_id).first_name %></td>
        <td><%= Chapter.find(news.chapter_id).name %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

COYI/app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

COYI/app/views/news/index.html.erb
<link rel="stylesheet" href="/Stylesheets/news.css">
<div class="top-of-page">
</div>
<div class="row news-title">
  <div class="col-md-10">
    <h1>News</h1>
    </div>
    <div class="col-md-2">
       <%= link_to 'New', new_news_path, :class => 'btn btn-outline-light btn-lg btn-block'%>
    </div>
  </div>
<%= render 'news/news_list' %>

COYI/app/views/news/new.html.erb
<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

COYI/app/views/news/show.html.erb
id="notice"><%= notice %></p>

<%= render 'news/show_news' %>

<div class="row">
 <div class="col-md-12 center-text title-style white-text">
   <%= link_to 'Back', news_index_path %>
 </div>
</div>