COYI/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#landing'
  devise_for :users, controllers: {registrations: 'users/registrations'}


  get 'askanexpert', to: 'ask_advocates#index', as: 'ask_expert'
  get 'profile/projects/new', to: 'projects#new', as: 'new_project'
  get 'profile/projects/:id', to: 'projects#show_user_project', as: 'show_user_project'


  get 'profile/my_resources/new', to: 'my_resources#new', as: 'new_my_resource'
  get 'profile/my_resources/:id', to: 'my_resources#show', as: 'show_user_my_resource'

  get 'circle/global',    to: 'circle#global',      as: 'global'
  get 'circle/advocate',  to: 'circle#advocate',    as: 'advocate'
  get 'circle/rules',     to: 'circle#rules',       as: 'rules'



  get 'home',             to: 'home#home',          as: 'home'

  get 'about',            to: 'about#about',        as: 'about'
  get 'contact',          to: 'about#contact',      as: 'contact'
  get 'faq',              to: 'about#faq',          as: 'faq'

  get 'resources',        to: 'my_resources#index', as: 'resources'

  get 'success',          to: 'success#success',    as: 'stories'

  get 'users',            to: 'profile#profile'

  resources :challenges
  resources :resources
  resources :my_resources
  resources :news
  resources :projects
  resources :chapters
  resources :ask_advocates


  get 'profile/projects', to: 'projects#user_projects', as: 'user_projects'
  get 'profile/my_resources', to: 'my_resources#user_my_resource', as: 'user_my_resources'
  get 'profile/me',         to: 'profile#profile',    as: 'user_profile'
  get 'users/me/edit',    to: 'devise/registrations#update'
  get 'users/:id',        to: 'profile#show'
  get 'chapter/news', to: 'news#chapter_news', as: 'chapter_news'


  resources :my_resources, only: [:create, :new]

  post 'contact', to: 'about#create'

end

COYI/app/models/project.rb
class Project < ApplicationRecord
  enum status: [:"Awaiting Approval", :Approved, :Rework, :Rejected]
  belongs_to :user
  has_one :chapter, through: :user
  validates :title, :description, presence: true
  has_many_attached :uploaded_files
  validates :title, length: { minimum: 8, too_short: "Title too short. Try and enter a descriptive title" }
  validates :title, length: { maximum: 30, too_long: "Title too long. %{count} characters is the maximum allowed"  }
end

COYI/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # Only allows logged in users to access those methods
  before_action :authenticate_user!, only: [:user_projects, :new, :edit, :create, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(status: 1)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end


  # GET /projects/1/edit
  def edit
  end

  def user_projects
    @projects = Project.where(user_id: current_user.id)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create!(project_params)
    @project.status = 0
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :status, uploaded_files: []).merge(user_id: current_user.id)
    end
end

COYI/app/helpers/projects_helper.rb
module ProjectsHelper
end

COYI/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-4 offset-4 text-on-bk-red white-text" style="border-radius:10px; ">

      <br>

      <div class="col-md-3 offset-3 field">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
      <br>
      <div class="col-md-3 offset-3 field">
        <%= form.label :description %>
        <%= form.text_field :description %>
      </div>
      <br>
      <div class="col-md-3 offset-3">
        <%= form.file_field :uploaded_files, multiple: true%>
      </div>
      <br>
      <div class="col-md-3 offset-3 actions">
        <%= form.submit %>
      </div>
      <br>
      <div class="top-of-page">

      </div>
    </div>
  </div>
<% end %>

COYI/app/views/projects/edit.html.erb
<div class="jumbotron jumbotron-fluid page-band-red">
  <div class="container">
    <img src="/images/user_placeholder_img.jpeg" class="user-profile-pic rounded-circle image-responsive" alt="Image of current user">
    <h2 class="text-on-bk">Edit Project </h2>
    <hr class="profile-hr">
  </div>
</div>


<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back to My Projects', projects_path %>

COYI/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Projects</h1>
<div style="margin:30px;" class="white-text text-on-bk-red pad">


  <div class="news-all">
      <% @projects.each do |project| %>
      <div class="news-band-white">
        <div class="no-margin row">

          <div class="col-md-6 news-title"><%= project.title %></div>
          <div class="col-md-6 news-title"><%= project.created_at %></div>
        </div>
        <div class="no-margin row news-body" style="color:black"  >
          <div class="col-md-9 offset-md-1 news-story"><%= project.description %></div>
          <div class="">
            <%= link_to 'Read More', project %><br/>
            <%= link_to 'Edit', edit_project_path(project) %><br/>
            <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
        <div>
          <ul class="admin-list">

          </ul>
        </div>
        <div class="no-margin row"style="color:black">
          <div class="col-md-4 offset-md-2 news-author">Published by: <%= project.user.first_name + " " + project.user.second_name %></div>
        </div>
      </div>
      <% end %>

  </div>

</div>

COYI/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', user_projects_path %>

COYI/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>  <%= @project.title %></h1>
</p>
<div class="container-fluid page-band-red">

  <div class="row">
    <div class="col-md-6 offset-3">

      <p>
        <strong>Current Status:</strong>
        <%= @project.status %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @project.description %>
      </p>

      <p>
        <strong>User:</strong>
        <%= @project.user.username %>
      </p>

      <p>
        <strong>Project Files:</strong>
        <ul>

    </div>
  </div>

</div>
</ul>
<% @project.uploaded_files.each do |file| %>
    <li>
      <a href="<%= rails_blob_path(file, disposition: "attachment")%>"  download>Download Project File</a>
    </li>
  <% end %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Projects Index', projects_path %> |
<%= link_to 'My Projects', user_projects_path %>

COYI/app/views/projects/user_projects.html.erb
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <!-- <img src="/images/user_placeholder_img.jpeg" class="user-profile-pic rounded-circle image-responsive" alt="Image of current user"> -->
      <h1> <%= current_user.first_name%>'s Projects</h1>
    </div> <!--end of container-->

  </div> <!--end of jtron-->

<div class="container">
  <div class="row">
    <div class="col-md-3 form-div" id="smooth-edges">
      <%= link_to 'New Project', new_project_path, :class => "btn btn-outline-light btn-lg btn-block" %>
      <%= link_to 'Back to My Profile', user_profile_path, :class => "btn btn-outline-light btn-lg btn-block" %>
    </div>
    <div class="col-md-8 offset-1 page-band-red text-on-bk" id="smooth-edges">
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= link_to project.title, project %></td>
              <td><%= link_to project.description, project %></td>
              <td><%= project.status %></td>
              <td><%= link_to 'Edit', edit_project_path(project) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div> <!--end of col-->
  </div>
</div>