COYI/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#landing'
  devise_for :users, controllers: {registrations: 'users/registrations'}


  get 'askanexpert', to: 'ask_advocates#index', as: 'ask_expert'
  get 'profile/projects/new', to: 'projects#new', as: 'new_project'
  get 'profile/projects/:id', to: 'projects#show_user_project', as: 'show_user_project'


  get 'profile/my_resources/new', to: 'my_resources#new', as: 'new_my_resource'
  get 'profile/my_resources/:id', to: 'my_resources#show', as: 'show_user_my_resource'

  get 'circle/global',    to: 'circle#global',      as: 'global'
  get 'circle/advocate',  to: 'circle#advocate',    as: 'advocate'
  get 'circle/rules',     to: 'circle#rules',       as: 'rules'



  get 'home',             to: 'home#home',          as: 'home'

  get 'about',            to: 'about#about',        as: 'about'
  get 'contact',          to: 'about#contact',      as: 'contact'
  get 'faq',              to: 'about#faq',          as: 'faq'

  get 'resources',        to: 'my_resources#index', as: 'resources'

  get 'success',          to: 'success#success',    as: 'stories'

  get 'users',            to: 'profile#profile'

  resources :challenges
  resources :resources
  resources :my_resources
  resources :news
  resources :projects
  resources :chapters
  resources :ask_advocates


  get 'profile/projects', to: 'projects#user_projects', as: 'user_projects'
  get 'profile/my_resources', to: 'my_resources#user_my_resource', as: 'user_my_resources'
  get 'profile/me',         to: 'profile#profile',    as: 'user_profile'
  get 'users/me/edit',    to: 'devise/registrations#update'
  get 'users/:id',        to: 'profile#show'
  get 'chapter/news', to: 'news#chapter_news', as: 'chapter_news'


  resources :my_resources, only: [:create, :new]

  post 'contact', to: 'about#create'

end

COYI/app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user

  validates_format_of :emailaddress,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates_format_of :firstname, :with => /\A[a-zA-Z]+\z/
  validates_format_of :lastname, :with => /\A[a-zA-Z]+\z/
  validates :location, :organisation, presence: true
end

COYI/app/controllers/admin/challenges_controller.rb
module Admin
  class ChallengesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Challenge.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Challenge.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

COYI/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /challenges
  # GET /challenges.json
  def index
    if current_user.access_level == 5
      @challenges = Challenge.all
    else
      @challenges = current_user.challenges
    end
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    @challenge.user = current_user
    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:emailaddress, :firstname, :lastname, :location, :organisation, :user_id)
    end
end

COYI/app/helpers/challenges_helper.rb
module ChallengesHelper
end

COYI/app/views/challenges/_form.html.erb
<%= form_with(model: challenge, local: true) do |form| %>

  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= form.label :emailaddress %>
    <%= form.text_field :emailaddress %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :organisation %>
    <%= form.text_field :organisation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

COYI/app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

COYI/app/views/challenges/index.html.erb
<p id="notice"><%= notice %></p>
<h1>100 Day Challenge</h1>
<p>You want to kick-start your own intrapreneur project within your company but don’t know where to begin? No panic, everyone can become a social super hero! We have developed a simple and free 100-day program for you to get all the basics right. You will receive new tips every 10 days to set up and move forward with your project.</p>

<table>
  <thead>
    <%if current_user.access_level == 5%>
    <tr>
      <th>Email address</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Location</th>
      <th>Organisation</th>
      <th colspan="3"></th>
    </tr>
    <%end%>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
          <td><%= challenge.emailaddress %></td>
          <td><%= challenge.firstname %></td>
          <td><%= challenge.lastname %></td>
          <td><%= challenge.location %></td>
          <td><%= challenge.organisation %></td>
          <td><%= link_to 'Show', challenge %></td>
          <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
          <td><%= link_to 'Unsubscribe', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

COYI/app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

COYI/app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emailaddress:</strong>
  <%= @challenge.emailaddress %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @challenge.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @challenge.lastname %>
</p>

<p>
  <strong>Location:</strong>
  <%= @challenge.location %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @challenge.organisation %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>